version: 2
updates:
# Create PRs for dependency updates
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
# Create PRs for golang version updates
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly