version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  default: none # standard/all/none/fast
  enable:
    - errcheck
    - gocritic
    - govet
    - nlreturn
    - revive
    - staticcheck
    - unused
    - whitespace
    - wsl
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: var-naming
      - path: (.+)\.go$
        text: dot-imports
      - path: (.+)\.go$
        text: package-comments
      - path: (.+)\.go$
        text: indent-error-flow
      - path: (.+)\.go$
        text: unexported-return
      - path: (.+)\.go$
        text: 'exported: (type|func) name will be used as .* by other packages, and that stutters;'
      - path: (.+)\.go$
        text: 'undeclared name: `.*`'
      - path: (.+)\.go$
        text: '".*" imported but not used'
    paths:
      - hack/.*
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(kube-rbac-proxy-watcher)
