# This workflow will run project tests

name: Unit tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Test
      run: |
        go mod download
        mkdir -p /tmp/blobs.d
        go tool gotestsum --format github-actions |& tee /tmp/blobs.d/gotestsum.txt
        tar czf /tmp/blobs.d/gotestsum.tar.gz -C /tmp/blobs.d gotestsum.txt
    - name: add-unit-test-to-component-descriptor
      uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
      with:
        blobs-directory: /tmp/blobs.d
        ocm-resources: |
          name: test-results
          relation: local
          access:
            type: localBlob
            localReference: gotestsum.tar.gz
          labels:
            - name: gardener.cloud/purposes
              value:
                - test
    - name: Report failure
      uses: nashmaniac/create-issue-action@v1.2
      # Only report failures of pushes (PRs are visible through the Checks section) to the default branch
      if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        title: 🐛 Unit tests failed for ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        labels: kind/bug
        body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
